import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync,spawnSync,spawn} from 'node:child_process';
import {dispatch,validate,POLICY} from './client.mjs';
if(process.platform!=='darwin'){console.log('INSTALLATION_DEPENDENT: native Gate B tests require macOS; no enforcement PASS claimed.');process.exit(0);}
const root=fs.mkdtempSync('/private/tmp/rnfs-broker-test-');
const here=path.dirname(new URL(import.meta.url).pathname);
const bundle=path.join(root,'bundle'),state=path.join(root,'state'),keys=path.join(root,'keys');
for(const p of [bundle,state,keys,path.join(state,'runs')]) fs.mkdirSync(p,{mode:p===keys?0o750:0o700});
const bin=path.join(bundle,'broker');
execFileSync('/usr/bin/xcrun',['clang','-fobjc-arc','-Wall','-Wextra','-Werror','-Wno-deprecated-declarations','-framework','Foundation','-DTESTING',`-DBUNDLE="${bundle}"`,`-DSTATE="${state}"`,`-DKEYS="${keys}"`,path.join(here,'broker.m'),'-o',bin]);
const verifier=path.join(bundle,'verify');
execFileSync('/usr/bin/xcrun',['clang','-fobjc-arc','-Wall','-Wextra','-Werror','-framework','Foundation','-DTESTING',`-DSTATE="${state}"`,`-DKEYS="${keys}"`,path.join(here,'verify.m'),'-o',verifier]);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const key=crypto.randomBytes(32); fs.writeFileSync(path.join(keys,'receipt.key'),key,{mode:0o440});
fs.copyFileSync(path.join(here,'fixture.dat'),path.join(bundle,'fixture.dat'));
fs.writeFileSync(path.join(state,'operation.lock'),'');fs.chmodSync(path.join(state,'operation.lock'),0o660);
const config={policyVersion:POLICY,brokerSha256:hash(fs.readFileSync(bin)),fixtureSha256:hash(fs.readFileSync(path.join(bundle,'fixture.dat'))),keyId:hash(key)};
const configPath=path.join(bundle,'policy.json'); const save=()=>fs.writeFileSync(configPath,JSON.stringify(config));save();
const req=(op='readiness_check')=>({operation:op,policyVersion:POLICY,requestId:crypto.randomUUID()});
const canonical=o=>JSON.stringify(Object.fromEntries(Object.entries(o).sort(([a],[b])=>a.localeCompare(b))));
let passed=0;
const check=(name,fn)=>{fn();passed++;console.log(`PASS ${name}`);};
const invoke=(r,args=[],raw=false)=>{const p=spawnSync(bin,args,{input:(raw?r:canonical(r))+'\n',encoding:'utf8',timeout:20000});if(p.error)throw p.error;return {status:p.status,value:JSON.parse(p.stdout)};};
const verify=receipt=>crypto.timingSafeEqual(Buffer.from(receipt.hmacSha256,'base64'),crypto.createHmac('sha256',key).update(Buffer.from(receipt.payloadBase64,'base64')).digest());
let receipt;
check('valid readiness and bound authenticated receipt',()=>{const r=req(); const out=invoke(r);assert.equal(out.status,0,JSON.stringify(out));receipt=out.value;assert(verify(receipt));const p=JSON.parse(Buffer.from(receipt.payloadBase64,'base64'));assert.equal(p.requestId,r.requestId);assert.equal(p.operation,r.operation);assert.equal(p.enforcement,'TEST_ONLY_UNCONFINED');assert.equal(p.inputHashes.request,hash(canonical(r)));assert.equal(p.configurationSha256,hash(fs.readFileSync(configPath)));assert.equal(invoke(r).value.code,'REPLAY_OR_RUN_INVALID');});
check('valid isolated backup restore bytes',()=>{const r=req('backup_restore_verify');const out=invoke(r);assert.equal(out.status,0,JSON.stringify(out));assert(verify(out.value));assert.deepEqual(fs.readFileSync(path.join(state,'runs',r.requestId,'restored.dat')),fs.readFileSync(path.join(bundle,'fixture.dat')));});
check('system dependency closure and substituted runtime path',()=>{
 assert.equal(spawnSync('/bin/sh',[path.join(here,'check-dependencies.sh'),bin]).status,0);
 const hostile=path.join(bundle,'hostile');execFileSync('/usr/bin/xcrun',['clang','-fobjc-arc','-framework','Foundation','-DTESTING',`-DBUNDLE="${bundle}"`,`-DSTATE="${state}"`,`-DKEYS="${keys}"`,'-Wl,-rpath,/private/tmp/caller-writable',path.join(here,'broker.m'),'-o',hostile]);
 assert.notEqual(spawnSync('/bin/sh',[path.join(here,'check-dependencies.sh'),hostile]).status,0);
 assert.notEqual(spawnSync('/bin/sh',[path.join(here,'check-dependencies.sh'),path.join(bundle,'missing')]).status,0);
});
const attacks={unknown_operation:{operation:'collect'},extra_argument:{args:['--unsafe']},malformed_schema:{requestId:123},shell_injection:{operation:'readiness_check; touch /tmp/evil'},executable_substitution:{executable:'/bin/sh'},traversal:{requestId:'../escape'},absolute_escape:{requestId:'/private/tmp/escape'},unexpected_input:{input:'fixture.dat'},unexpected_output:{output:'restore.dat'},production_data:{input:'/Users/lukesmacminim41/Documents/royal-navy-fleet-status/data/royal-navy/vessels.json'},private_user_data:{input:'/Users/lukesmacminim41/.ssh/id_ed25519'},newline_id:{requestId:crypto.randomUUID()+'\n'}};
for(const [name,patch] of Object.entries(attacks))check(name,()=>assert.equal(invoke({...req(),...patch}).status,1));
check('caller command line rejected',()=>assert.equal(invoke(req(),['/bin/sh']).value.code,'ARGUMENTS'));
for(const text of ['[]','null','{broken','{"operation":"bad","operation":"readiness_check","policyVersion":"rnfs-gate-b-v1","requestId":"'+crypto.randomUUID()+'"}']) check('malformed or duplicate JSON',()=>assert.equal(invoke(text,[],true).status,1));
check('symlink input rejected',()=>{const p=path.join(bundle,'fixture.dat');fs.renameSync(p,p+'.saved');fs.symlinkSync(p+'.saved',p);assert.equal(invoke(req()).status,1);fs.unlinkSync(p);fs.renameSync(p+'.saved',p);});
check('symlink output run rejected',()=>{const r=req();fs.symlinkSync(root,path.join(state,'runs',r.requestId));assert.equal(invoke(r).status,1);fs.unlinkSync(path.join(state,'runs',r.requestId));});
check('symlink root rejected',()=>{fs.renameSync(keys,keys+'.saved');fs.symlinkSync(keys+'.saved',keys);assert.equal(invoke(req()).status,1);fs.unlinkSync(keys);fs.renameSync(keys+'.saved',keys);});
check('hardlink input rejected',()=>{const p=path.join(bundle,'fixture.dat');fs.linkSync(p,p+'.link');assert.equal(invoke(req()).status,1);fs.unlinkSync(p+'.link');});
check('ACL rejected',()=>{const p=path.join(bundle,'fixture.dat');execFileSync('/bin/chmod',['+a',`${os.userInfo().username} allow write`,p]);assert.equal(invoke(req()).value.code,'ACL');execFileSync('/bin/chmod',['-N',p]);});
check('key mode rejected',()=>{const p=path.join(keys,'receipt.key');fs.chmodSync(p,0o444);assert.equal(invoke(req()).value.code,'KEY_MODE');fs.chmodSync(p,0o440);});
check('receipt alteration rejected',()=>assert(!verify({...receipt,payloadBase64:Buffer.from('{}').toString('base64')})));
check('forged receipt rejected',()=>assert(!verify({...receipt,hmacSha256:crypto.randomBytes(32).toString('base64')})));
check('native administrator verifier authenticates and rejects altered/forged receipts',()=>{
 const payload=JSON.parse(Buffer.from(receipt.payloadBase64,'base64')),id=payload.requestId,p=path.join(state,'runs',id,'receipt.json');
 assert.equal(spawnSync(verifier,[id]).status,0);
 fs.writeFileSync(p,JSON.stringify({...receipt,payloadBase64:Buffer.from('{}').toString('base64')}));assert.equal(spawnSync(verifier,[id]).status,1);
 fs.writeFileSync(p,JSON.stringify({...receipt,hmacSha256:crypto.randomBytes(32).toString('base64')}));assert.equal(spawnSync(verifier,[id]).status,1);
 fs.writeFileSync(p,JSON.stringify(receipt));
});
check('modified config rejected',()=>{fs.writeFileSync(configPath,JSON.stringify({...config,policyVersion:'tampered'}));assert.equal(invoke(req()).status,1);save();});
check('modified fixture rejected',()=>{fs.appendFileSync(path.join(bundle,'fixture.dat'),'tamper');assert.equal(invoke(req()).value.code,'FIXTURE_INTEGRITY');fs.copyFileSync(path.join(here,'fixture.dat'),path.join(bundle,'fixture.dat'));});
check('modified approved executable hash rejected',()=>{fs.writeFileSync(configPath,JSON.stringify({...config,brokerSha256:'0'.repeat(64)}));assert.equal(invoke(req()).value.code,'INTEGRITY');save();});
// Real independent holder process; kill without unlocking, kernel must release flock.
const holder=spawn('python3',['-u','-c','import fcntl,sys,time; f=open(sys.argv[1],"r+"); fcntl.flock(f,fcntl.LOCK_EX); print("locked",flush=True); time.sleep(60)',path.join(state,'operation.lock')],{stdio:['ignore','pipe','inherit']});
await new Promise(resolve=>holder.stdout.once('data',resolve));
check('independent process duplicate excluded',()=>assert.equal(invoke(req()).value.code,'BUSY'));
const ended=new Promise(resolve=>holder.once('exit',resolve));holder.kill('SIGKILL');await ended;
check('kernel releases crashed process lock',()=>assert.equal(invoke(req()).status,0));
const duplicate=req('backup_restore_verify');
const launch=()=>new Promise((resolve,reject)=>{const p=spawn(bin,[],{stdio:['pipe','pipe','inherit']});let output='';p.stdout.on('data',b=>output+=b);p.on('error',reject);p.on('exit',status=>resolve({status,value:JSON.parse(output)}));p.stdin.end(canonical(duplicate)+'\n');});
const simultaneous=await Promise.all([launch(),launch()]);
check('two independent broker clients same run: exactly one success',()=>assert.equal(simultaneous.filter(x=>x.status===0).length,1));
check('storage capacity fails closed',()=>{for(let i=0;i<256;i++)fs.mkdirSync(path.join(state,'runs','cap-'+i));assert.equal(invoke(req()).value.code,'CAPACITY');});
assert(validate('readiness_check',req()));
const reply=await dispatch({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'readiness_check',arguments:req(),_meta:{progressToken:1}}},async()=>receipt);assert.equal(reply.result.isError,false);passed++;
console.log(`PASS ${passed} tests; fixture-only TESTING binary. Dedicated identity, protected ownership, actual network/filesystem sandbox, launchd transport and scheduler: INSTALLATION_DEPENDENT.`);
fs.rmSync(root,{recursive:true,force:true});
